# Generated by Django 5.1.1 on 2024-09-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('age', models.PositiveIntegerField()),
                ('bio', models.TimeField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
